### ISSUE TITLE
Publish `redmine_expo_push` plugin:

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_expo_push#2]
- [x] use branch `main`
- [x] has branch `develop`
- [x] has tests (if not create issue)
- [ ] has CI with GH Actions (if not create issue)
- [x] has `LICENSE`
- [x] has `README.md`
- [x] comments are in English (if not create issue)

**Comment by sanak** [comment]
The plugin is already published, so I close this with creating CI with GH Actions issue.
